# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de86a2d887100908a52e270676c9c315536af801b629149649834f7575cfcd1afddc8ae5aae53962b89c056dcbe29b4fea44f8d1416ae265e87ba2953d366dc

test:
  secret_key_base: 190803c60d48f968a7f5f8bcf3f824bfe87cf9e7cae6af9cd24cc2dbe5de95424e2a4973c3d08325ea369d2a61cd6c420cc0a6dc2bc314608b391a97a3901cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
